### ISSUE TITLE
第一屆 CodeTengu 一句話笑話比賽

### ISSUE THREAD

**Issue by vinta** [CodeTengu/headquarters#23]
大家都知道咱們 [CodeTengu Weekly](http://weekly.codetengu.com/) 每一期的標題都是一句玩笑話，但是因為最近已經快把庫存的笑話用完了，地方的 CodeTengu 需要幫助，遂決定舉辦「第一屆 CodeTengu 一句話笑話比賽」！不然哪天笑話用完了，CodeTengu Weekly 就要停刊了。

最好是一句話就可以表達的程序員笑話，畢竟是要拿來當 weekly 標題的。

**以下開放投稿！**

**Comment by wancw** [comment]
「聖誕節要到了」放 10/26 那期？

**Comment by saiday** [comment]
是 Oct(31) = Dec(25) 那個笑話嗎，好高端哦！

**Comment by vinta** [comment]
哈哈哈哈好！

**Comment by wancw** [comment]
每年都要講一次的老哏，我已經毫無創意了。

是說，前陣子在《知乎日報》看到一則巴別塔的程式語言版感覺還不錯。

**Comment by vinta** [comment]
最近看到一個最好笑的：

> 如果 Java 真的有 Garbage Collection 的話，大部份的程式應該在剛開始執行的時候就把自己給回收了

**Comment by tzangms** [comment]
哈哈哈 這個有點強
2015年10月12日 上午5:46於 "Vinta" <notifications@github.com>寫道：

**Comment by kkc** [comment]
提供一個前公司的 Bot 常講的笑話:  
>程式設計師最討厭康熙的哪個兒子？ 答：胤禩。因為他是八阿哥

**Comment by saiday** [comment]
If you give a person a program, you'll frustrate him for a day. If you teach a person to program, you will frustrate them for a lifetime!

**Comment by vinta** [comment]
剛好看到 http://www.reddit.com/r/sysadmin/comments/2zh8v2/lets_tell_jokes_what_are_the_sysadmins_favourite/

**Comment by fukuball** [comment]
強耶，討論串一堆笑話！

**Comment by JuanitoFatas** [comment]
[CSS Puns & CSS Jokes](http://saijogeorge.com/css-puns)

**Comment by FrankNine** [comment]
http://stackoverflow.com/questions/184618/what-is-the-best-comment-in-source-code-you-have-ever-encountered

#define TRUE FALSE
//Happy debugging suckers

**Comment by FrankNine** [comment]
QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.
Source: https://twitter.com/sempf/status/514473420277694465

**Comment by abookyun** [comment]
世界上只有 `10` 種人，一種是懂 binary 的另一種不懂。

原文：`"There are only 10 types of people in the world: those who understand binary, and those who don't."`

出處：https://en.wikipedia.org/wiki/Mathematical_joke

**Comment by RenCheng0525** [comment]
Programs = Algorithms + Data Structures + (Bugs + Tears)

**Comment by M157q** [comment]
https://github.com/pyjokes/pyjokes/blob/master/pyjokes/jokes_en.py

前陣子看到的 我覺得裏面蠻多都還不錯
隨便貼幾個然後順手翻譯一下，翻譯不到位的話請見諒

+ How do you generate a random string? Put a first year Computer Science student in Vim and ask them to save and exit.
    + 「如何產生一個隨機字串？打開 Vim，叫一個大一資工系學生儲存檔案後離開。」
+ Triumphantly, Beth removed Python 2.7 from her server in 2020. 'Finally!' she said with glee, only to see the announcement for Python 4.4.
    + 「『終於！』2020年，Beth 成功從她的伺服器上去除了 Python 2.7 後，難掩興奮得脫口而出。直到她看見了 Python 4.4 釋出...」
+ If you play a Windows CD backwards, you'll hear satanic chanting ... worse still, if you play it forwards, it installs Windows.
    + 「如果你把一片 Windows CD 反著播放，你會聽到撒旦之歌。但更恐怖的是，如果你正著播放，它會安裝 Windows 在你電腦上。」
+ 'Knock, knock.' 'Who's there?' ... very long pause ... 'Java.'
    + 「『叩叩叩！』『是誰？』（過了很長一段時間）『Java。』」
+ Software developers like to solve problems. If there are no problems handily available, they will create their own problems.
    + 「軟體工程師喜歡解決問題，如果手邊沒有問題可以解決的話，他們會為自己製造問題。」
+ .NET was named .NET so that it wouldn't show up in a Unix directory listing.
    + 「.NET 之所以命名為 .NET 是因為這樣它就不會出現在 Unix `ls` 指令的結果中。」
+ Hardware: The part of a computer that you can kick.
    + 「硬體：電腦的組成中，你可以用腳踹的部份。」
+ In C we had to code our own bugs. In C++ we can inherit them.
    + 「在 C 裡，我們必須自己寫 bug；在 C++ 裡，我們可以直接繼承 bug。」(方便多了)
+ How come there is not obfuscated Perl contest? Because everyone would win.
    + 「為什麼 Perl 沒有代碼混淆比賽？因為每位參賽者都會是贏家。」
+ How many programmers does it take to kill a cockroach? Two: one holds, the other installs Windows on it.
    + 「需要幾位程式設計師才能殺掉一隻蟑螂？『兩個。』一個抓住蟑螂，另一個在蟑螂身上安裝 Windows。」
+ If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl.
    + 「如果你把一百萬隻猴子放在一百萬把鍵盤上，其中一隻猴子最終會寫出 Java 程式碼，其餘的則會寫出 Perl 程式碼。」

應該夠用一陣子了?

想要自己笑一笑的就 `pip install pyjokes` 或 `pip3 install pyjokes`
裝完後直接打 `pyjoke` 就會隨機顯示一則笑話了
蠻適合放在 motd 的XD

裏面有提到笑話的來源是這篇 http://stackoverflow.com/questions/234075/what-is-your-best-programmer-joke

**Comment by vinta** [comment]
@M157q 哈哈哈哈哈這些好！

**Comment by tzangms** [comment]
@M157q 這個強!

**Comment by amowu** [comment]
碼農 -> 程序猿 -> 攻城獅 -> 後端攻城獅 -> 前端攻城獅 -> 全端攻城獅 -> [無端](http://www.csdn.net/article/2015-12-03/2826382-SDCC)攻城獅 -> 達文西

**Comment by fukuball** [comment]
酷耶～

**Comment by kkc** [comment]
@M157q pyjokes 好厲害啊！

**Comment by puff-tw** [comment]
我認為一年一度的員工建康檢查，根本是找工作的重要參考指標，另一項是，Steam 的遊玩時數，恰好可以說明 work life balance 的重要依據啊!!

**Comment by sexyoung** [comment]
昨天感冒又拉肚子晚上失眠又想吐，結果今天早上起床寫個code全都好了耶

**Comment by M157q** [comment]
"Perl – The only language that looks the same before and after RSA encryption." - Keith Bostic
「Perl：唯一一個 RSA 加密前後看起來一模一樣的語言。」

ref: http://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html

**Comment by M157q** [comment]
“In C++ it’s harder to shoot yourself in the foot, but when you do, you blow off your whole leg.” (Bjarne Stroustrup)
「在 C++ 中，你沒那麼容易射傷自己的腳，但要是你不小心這麼做了，你會炸掉整條腿。」（C++ 之父 Bjarne Stroustrup）

ref: http://www.devtopics.com/101-great-computer-programming-quotes/

**Comment by genxstylez** [comment]
強強的!

**Comment by fukuball** [comment]
Perl 也被酸得太厲害～

**Comment by M157q** [comment]
"There are two ways to write error-free programs; only the third one works."
「有兩種方法可以寫出沒有錯誤的程式，但只有第三種方法有效。」

**Comment by bcse** [comment]
"Whats the object-oriented way to become wealthy?"
A: Inheritance
「如何以物件導向的方式變得富有？」答：「繼承。」

**Comment by kevingo** [comment]
pyjokes 好讚 XD

**Comment by Po-Jen** [comment]
「眾裡尋他千百度，驀然回首，那人卻在軟體開發部。」

**Comment by cosmtrek** [comment]
@Po-Jen 哈哈。

**Comment by ccc-larc** [comment]
(尚未徵得作者同意)
來源：https://twitter.com/panda_extral/status/695442044429307907

    batman 用什么电脑？
    当然是 windows
    因为用了 Mac 他就要改名叫 bashman 了。

**Comment by theJian** [comment]
c = ( a != b ) ? a : b;

**Comment by mingderwang** [comment]
[你知道爲何 Java 程式設計師戴眼鏡嗎? ](http://i.imgur.com/460nJ.jpg)

**Comment by uranusjr** [comment]
我在星期五下班前 deploy 花了一週完成的程式 [#然後它就死掉了](http://www.appledaily.com.tw/realtimenews/article/new/20160414/838908/)

**Comment by fukuball** [comment]
很多网站的登录界面上都有一句诗：记住我 忘记密码

**Comment by fukuball** [comment]
技術教學或分享也是一種劇透，而且通常不會有人說「你雷到我了！」

**Comment by kkdai** [comment]
最近的技術時事梗:  「Swift 從入門到重學，到又要重學。」

**Comment by uranusjr** [comment]
In case of fire:

1. git commit
2. git push
3. leave building

https://github.com/qw3rtman/git-fire

**Comment by fukuball** [comment]
「這樣不就是在解技術債的時候還欠技術債嗎」
「你看過大賣空嗎，這就是技術債的技術債，算是一種衍生性技術債」

**Comment by uranusjr** [comment]
除錯就像是推理劇，你擔任偵探主角，同時也是兇手。
